### ISSUE TITLE
No way to see which users are inserted into the textarea

### ISSUE THREAD

**Issue by aaronorosen** [lodev09/bootstrap-suggest#21]
It seems like there is not an easy way to detect which users have been selected and are present in the textarea as users can be deleted directly from the textarea.

**Comment by aaronorosen** [comment]
support should be easy to add for this once #14  is implemented.

**Comment by lodev09** [comment]
You can get the selected users via regex (JS or server side), which might not be that easy :)

I think support for this feature is not necessary for the plugin since the plugin is only intended for selecting items from a dropdown. Perhaps if #14 is implemented, we can format the text returned to the `div`.
